// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupermarketPrices.Infra.Context;

namespace SupermarketPrices.Api.Migrations
{
    [DbContext(typeof(SupermarketPricesDbContext))]
    partial class SupermarketPricesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SupermarketPrices.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Description")
                        .HasMaxLength(120)
                        .HasColumnType("text");

                    b.Property<string>("EAN")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("SKU")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("SupermarketPrices.Domain.Entities.Supermarket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Supermarket");
                });

            modelBuilder.Entity("SupermarketPrices.Domain.Entities.SupermarketProduct", b =>
                {
                    b.Property<int>("SupermarketId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasMaxLength(120)
                        .HasColumnType("Date");

                    b.Property<decimal>("Price")
                        .HasMaxLength(120)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SupermarketId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("SupermarketProduct");
                });

            modelBuilder.Entity("SupermarketPrices.Domain.Entities.SupermarketProduct", b =>
                {
                    b.HasOne("SupermarketPrices.Domain.Entities.Product", null)
                        .WithMany("SupermarketProduct")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketPrices.Domain.Entities.Supermarket", null)
                        .WithMany("SupermarketProduct")
                        .HasForeignKey("SupermarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupermarketPrices.Domain.Entities.Product", b =>
                {
                    b.Navigation("SupermarketProduct");
                });

            modelBuilder.Entity("SupermarketPrices.Domain.Entities.Supermarket", b =>
                {
                    b.Navigation("SupermarketProduct");
                });
        }
    }
}
